[project]
name = "alphaagents"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "crewai>=0.177.0",
    "pandas>=2.3.2",
    "yfinance>=0.2.65",
]
